package keychain

type RecordTypes uint32

const (
	CSSM_DL_DB_SCHEMA_INFO RecordTypes = iota
	CSSM_DL_DB_SCHEMA_INDEXES
	CSSM_DL_DB_SCHEMA_ATTRIBUTES
	CSSM_DL_DB_SCHEMA_PARSING_MODULE
)

const (
	CSSM_DL_DB_RECORD_ANY RecordTypes = iota + 0x0000000a
	CSSM_DL_DB_RECORD_CERT
	CSSM_DL_DB_RECORD_CRL
	CSSM_DL_DB_RECORD_POLICY
	CSSM_DL_DB_RECORD_GENERIC
	CSSM_DL_DB_RECORD_PUBLIC_KEY
	CSSM_DL_DB_RECORD_PRIVATE_KEY
	CSSM_DL_DB_RECORD_SYMMETRIC_KEY
	CSSM_DL_DB_RECORD_ALL_KEYS
)

const (
	CSSM_DL_DB_RECORD_GENERIC_PASSWORD RecordTypes = 0x80000000 + iota
	CSSM_DL_DB_RECORD_INTERNET_PASSWORD
	CSSM_DL_DB_RECORD_APPLESHARE_PASSWORD
	CSSM_DL_DB_RECORD_USER_TRUST
	CSSM_DL_DB_RECORD_X509_CRL
	CSSM_DL_DB_RECORD_UNLOCK_REFERRAL
	CSSM_DL_DB_RECORD_EXTENDED_ATTRIBUTE
)

const CSSM_DL_DB_RECORD_X509_CERTIFICATE RecordTypes = iota + 0x80001000
const CSSM_DL_DB_RECORD_METADATA RecordTypes = iota + 0x80008000

func (rt RecordTypes) String() string {
	switch rt {
	case CSSM_DL_DB_SCHEMA_INFO:
		return "CSSM_DL_DB_SCHEMA_INFO"
	case CSSM_DL_DB_SCHEMA_INDEXES:
		return "CSSM_DL_DB_SCHEMA_INDEXES"
	case CSSM_DL_DB_SCHEMA_ATTRIBUTES:
		return "CSSM_DL_DB_SCHEMA_ATTRIBUTES"
	case CSSM_DL_DB_SCHEMA_PARSING_MODULE:
		return "CSSM_DL_DB_SCHEMA_PARSING_MODULE"
	case CSSM_DL_DB_RECORD_ANY:
		return "CSSM_DL_DB_RECORD_ANY"
	case CSSM_DL_DB_RECORD_CERT:
		return "CSSM_DL_DB_RECORD_CERT"
	case CSSM_DL_DB_RECORD_CRL:
		return "CSSM_DL_DB_RECORD_CRL"
	case CSSM_DL_DB_RECORD_POLICY:
		return "CSSM_DL_DB_RECORD_POLICY"
	case CSSM_DL_DB_RECORD_GENERIC:
		return "CSSM_DL_DB_RECORD_GENERIC"
	case CSSM_DL_DB_RECORD_PUBLIC_KEY:
		return "CSSM_DL_DB_RECORD_PUBLIC_KEY"
	case CSSM_DL_DB_RECORD_PRIVATE_KEY:
		return "CSSM_DL_DB_RECORD_PRIVATE_KEY"
	case CSSM_DL_DB_RECORD_SYMMETRIC_KEY:
		return "CSSM_DL_DB_RECORD_SYMMETRIC_KEY"
	case CSSM_DL_DB_RECORD_ALL_KEYS:
		return "CSSM_DL_DB_RECORD_ALL_KEYS"
	case CSSM_DL_DB_RECORD_GENERIC_PASSWORD:
		return "CSSM_DL_DB_RECORD_GENERIC_PASSWORD"
	case CSSM_DL_DB_RECORD_INTERNET_PASSWORD:
		return "CSSM_DL_DB_RECORD_INTERNET_PASSWORD"
	case CSSM_DL_DB_RECORD_APPLESHARE_PASSWORD:
		return "CSSM_DL_DB_RECORD_APPLESHARE_PASSWORD"
	case CSSM_DL_DB_RECORD_USER_TRUST:
		return "CSSM_DL_DB_RECORD_USER_TRUST"
	case CSSM_DL_DB_RECORD_X509_CRL:
		return "CSSM_DL_DB_RECORD_X509_CRL"
	case CSSM_DL_DB_RECORD_UNLOCK_REFERRAL:
		return "CSSM_DL_DB_RECORD_UNLOCK_REFERRAL"
	case CSSM_DL_DB_RECORD_EXTENDED_ATTRIBUTE:
		return "CSSM_DL_DB_RECORD_EXTENDED_ATTRIBUTE"
	case CSSM_DL_DB_RECORD_X509_CERTIFICATE:
		return "CSSM_DL_DB_RECORD_X509_CERTIFICATE"
	case CSSM_DL_DB_RECORD_METADATA:
		return "CSSM_DL_DB_RECORD_METADATA"
	default:
		return "UNKNOWN"
	}
}
